name: .NET CI

on:
  push:
    branches: dev
  pull_request:
    branches: [ master, dev ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Add VSTest.console.exe to the PATH
      uses: darenm/Setup-VSTest@v1

    - name: Run functional tests
      run: vstest.console.exe "TestProject1\bin\Release\net6.0\TestProject1.dll"
