name: .NET Continuous Integration

on:
  push:
    branches: dev
  pull_request:
    branches: [ master, dev ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run Web App in background and run tests
      run: |
        cd petStoreMonitoringApp
        dotnet build --configuration Release --no-restore
        Start-Process ./bin/Release/net6.0/petStoreMonitoringApp.exe -NoNewWindow -PassThru
        cd ..
        dotnet test --no-restore --verbosity normal
