name: .NET CI

on:
  push:
    branches: dev
  pull_request:
    branches: [ master, dev ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Download Chrome Driver
      run: sudo apt-get -yqq install chromium-chromedriver
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Run web app
      run: dotnet petStoreMonitoringApp/bin/Debug/net6.0/petStoreMonitoringApp.dll
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
